Feature add forms
Buyaki01/re-former pull request #1
Opened 2020-07-20 14:56 UTC by Bluette1

# Project Re-former
- [Requirements](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms)
- This project is about 
  - Creating and using forms in Rails
  - Creating View templates in Rails

2020-07-21 18:03 UTC, wathigo requested changes
### Changes Required.
Great work on this project :clap:
Almost all requirements have been met.

Let's fix one issue in comments before proceeding to the next project.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-07-21 18:03 UTC, wathigo commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path
**REQUIRED**
* Redirect to `edit_user_path` if user was saved ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_update.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-07-22 06:10 UTC, mosesogwo approved these changes
**Thank you for making the change requested.:+1: Your project is approved**

You can now merge the PR

**Good luck in your next project:stars:**

### Status: Approved :heavy_check_mark:

2020-07-22 07:38 UTC, Bluette1 commented
@wathigo  and @mosesogwo: Thank you very much for your feedback!

2020-07-22 07:38 UTC, merged